server:
  port: 16000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      #配置gateway的路由功能
      routes:
        #路由ribbon
        - id: consumer1
          uri: lb://CONSUMER-RIBBON
          #如何判断当前请求是要访问ribbon的
          predicates:
            - Path=/a/**
          filters:
            - StripPrefix=1
        #路由feign
        - id: consumer2
          uri: lb://CONSUMER-FEIGN
          predicates:
            - Path=/b/**
          filters:
            - StripPrefix=1

#注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://www.aaa.com:10000/eureka,http://www.bbb.com:10001/eureka,http://www.ccc.com:10002/eureka

